### PR TITLE
Update allows a user to select the user from a dropdown

### PR DESCRIPTION
**Pull request by cwuensche**
Fixes issue #33

### CODE REVIEW

**Review by corsacca — CHANGES_REQUESTED** [review]
Thanks @cwuensche!
Please restrict the select to the users that have the access_contacts capability.
And set the default user to be the base user. See `dt_get_base_user`

**Comment by cwuensche** [comment]
@corsacca New commit addresses these suggestions.

**Comment by corsacca** [comment]
Thanks @cwuensche 

If i select a user and update the form, the select input reverts back to the default user. Please update the select to display the selected user when that value is present.

**Comment by corsacca** [comment]
Thank you @cwuensche ! Looks great!

**Review by corsacca — APPROVED** [review]

**Pull request merged**
